android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
GROUP=io.github.nadheria
POM_ARTIFACT_ID=growbolt-sdk
VERSION_NAME=1.0.0
POM_NAME=Growbolt SDK
POM_DESCRIPTION=Growbolt Offerwall SDK for Android
POM_URL=https://github.com/growbolt/growbolt-android-sdk
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_DEVELOPER_ID=growbolt
POM_DEVELOPER_NAME=Growbolt
POM_DEVELOPER_URL=https://growbolt.com
POM_SCM_URL=https://github.com/growbolt/growbolt-android-sdk
POM_SCM_CONNECTION=scm:git:github.com/growbolt/growbolt-android-sdk.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/growbolt/growbolt-android-sdk.git



mavenCentralUsername=JjWs5e
mavenCentralPassword=E9P7d2rmfOfobuKmtYmeBjO7xKUcTw1U0

signing.gnupg.keyName=FF513323
signing.gnupg.passphrase=Roger1379

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

#
#<server>
#<id>${server}</id>
#<username>JjWs5e</username>
#<password>E9P7d2rmfOfobuKmtYmeBjO7xKUcTw1U0</password>
#</server>
